### ISSUE TITLE
Correct pytorch3D version?

### ISSUE THREAD

**Issue by RobinRenggli** [YudongGuo/AD-NeRF#1]
I'm having issues installing pytorch3D in the conda environment you provided. Using "conda install pytorch3d -c pytorch3d" doesn't work, I suspect it has something to do with the python, cuda, pytorch and torchvision version.

Could you kindly let me know, which installation method you used, so I can follow the same steps, it might save me a lot of trouble.

**Comment by YudongGuo** [comment]
Hi, I installed pytorch3d from a local clone by running:
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e .

**Comment by RobinRenggli** [comment]
Thank you.

Sadly, I get several errors when I try to install pytorch3D in the environment you provided. I suspect it has to do with CUDA 11.

I am currently circumventing this issue by using a different environment with CUDA versions compatible with the conda install packages for pytorch3D, which seems to work (using the nightly build is necessary, otherwise there is a small bug; installing from a local clone is also the nightly version, so if your suggestion works for others, it should be fine).

Since I think this is the only place where pytorch3D is used, this seems like a simple way to avoid issues with pytorch3D, at least for me.

**Comment by RAJA-PARIKSHAT** [comment]
@RobinRenggli How did you manage to solve it. I have NVIDIA RTX A4000 with Cuda 11.3. It's taking me to set up the environment for it. Can you share your steps, please?

**Comment by UestcJay** [comment]
> @RobinRenggli How did you manage to solve it. I have NVIDIA RTX A4000 with Cuda 11.3. It's taking me to set up the environment for it. Can you share your steps, please?

Hi you can refer [this](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md)
