### ISSUE TITLE
Video FPS set to 50 in deepspeech_features.py

### ISSUE THREAD

**Issue by saslamsameja** [YudongGuo/AD-NeRF#10]
Hi @YudongGuo, I have noticed that the video fps is set to 50 for the generation of deepspeech features. Will this value be updated based on the FPS of our output? And I noticed by default the output video FPS is 25, then should this value not be 25?

**Comment by YudongGuo** [comment]
Hi, the setting in this repo is ok. For a 25fps video containing n frames, after extracting deepspeech features at 50fps (for example 2n*29 dims), for each frame in the video, I extract its surrounding 320ms audio features (so 16*29 audio feature for a frame). So the audio feature  corresponding to a frame is a surrounding audio features and there is no need for keeping same fps for them.
