### ISSUE TITLE
Which cuda and setup you use?

### ISSUE THREAD

**Issue by rebotnix** [YudongGuo/AD-NeRF#11]
Hi,

i would like to jump into this research and setup new fresh maschine with 2 x rtx 3090. I use cuda 11.2 and i have issue with deepseach setup.

Which version of cude do you use to run the obama demo?

Tensorflow 1.5.1 is working, but doenst support cuda 11.2. Minium for cuda 11.2/tensorflow seems version 2.x or higher, but deepspeech is not compabtible with that. 

This is my output when i use tensorflow 2.x or higher.

Issue output is:
Traceback (most recent call last):
  File "data_util/deepspeech_features/extract_ds_features.py", line 128, in <module>
    main()
  File "data_util/deepspeech_features/extract_ds_features.py", line 124, in main
    metainfo_file_path=args.metainfo)
  File "data_util/deepspeech_features/extract_ds_features.py", line 84, in extract_features
    deepspeech_pb_path=deepspeech_pb_path)
  File "/opt/3tbdrive1/experiments/AD-NeRF/data_util/deepspeech_features/deepspeech_features.py", line 42, in conv_audios_to_deepspeech
    deepspeech_pb_path)
  File "/opt/3tbdrive1/experiments/AD-NeRF/data_util/deepspeech_features/deepspeech_features.py", line 105, in prepare_deepspeech_net
    logits_ph = graph.get_tensor_by_name("deepspeech/logits:0")
  File "/opt/3tbdrive1/experiments/AD-NeRF/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3902, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/opt/3tbdrive1/experiments/AD-NeRF/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3726, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/opt/3tbdrive1/experiments/AD-NeRF/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3768, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'deepspeech/logits:0' refers to a Tensor which does not exist. The operation, 'deepspeech/logits', does not exist in the graph."

**Comment by YudongGuo** [comment]
Hi, my environment is also RTX 3090 with cuda 11.2. The deepspeech requires tensorflow 1.x and all my setup can be found in [environment.yml](https://github.com/YudongGuo/AD-NeRF/blob/master/environment.yml).

**Comment by rebotnix** [comment]
Hi, 

thanks for your answer. 

I take a look in the environment.yml, and Tensorflow 1.51.1 requires cuda 10.0 with all libcudart.so.10.0, libcublas.so.10.0..and so on. 

When you start with installed cuda 11.2, tensorflow 1.5.1 run into fallback to CPU mode, cause it can´t find the required 10.0 additional libaries. 

Out 
..Could not load dynamic library 'libcudart.so.10.0'; 
/usr/local/cuda-11.2/lib64
Could not load dynamic library 'libcublas.so.10.0'; 
Could not load dynamic library 'libcufft.so.10.0'; 
Could not load dynamic library 'libcurand.so.10.0'; 
Could not load dynamic library 'libcusolver.so.10.0';
Could not load dynamic library 'libcusparse.so.10.0'; 
Could not load dynamic library 'libcudnn.so.7'; 
..

When you install cuda 11.2 , then Tensorflow 2.x seems to required.

Do you setup a mixed library and set symbol links to 10.0 libas to make this project working?

Maybe you running in CPU instead of GPU or a mixed of both with seems to be very slow.

How does nvidia-smi looks when you render start the obama demo?

Thank you

**Comment by YudongGuo** [comment]
Hi, thanks for your reminding. I noticed that the GPU usage keeps 0% during the deepspeech running, so I guess it run in CPU mode instead.

**Comment by rebotnix** [comment]
Yeah, i think that´s why we have so slow output too, i try to fix deepspeech, but it seems that they dont´s support tensorflow 2.x.

**Comment by VishLivecoder** [comment]
Hey, What exactly did u do to resolve the issue?.

**Comment by cucdengjunli** [comment]
> Hi, my environment is also RTX 3090 with cuda 11.2. The deepspeech requires tensorflow 1.x and all my setup can be found in [environment.yml](https://github.com/YudongGuo/AD-NeRF/blob/master/environment.yml).

same question

**Comment by huangxin168** [comment]
same problem
