### ISSUE TITLE
Do I just have to run the torsoNeRF for the test for rendering?

### ISSUE THREAD

**Issue by rlgnswk** [YudongGuo/AD-NeRF#131]
Hello, 

Do I just have to run the torsoNeRF for the test for rendering with the command 
'''python NeRFs/TorsoNeRF/run_nerf.py --config dataset/$id/TorsoNeRFTest_config.txt --aud_file=dataset/$id/aud.npy --test_size=300''? 

Why did we learn the headNeRF separately, which you wrote like that in README?

BTW, thank you for sharing your work

**Comment by rlgnswk** [comment]
Finally, I got the process

**Comment by piwawa** [comment]
> Finally, I got the process

So why?

**Comment by rlgnswk** [comment]
Just follow "Run AD-NeRF for Rendering" of Readme. 

I was confused about the use of TorsoNeRF. But it is also used for the combined use of Head Part and Torso Part, depending on its arguments.
