### ISSUE TITLE
输出视频

### ISSUE THREAD

**Issue by feifeitu1** [YudongGuo/AD-NeRF#133]
请问用
python NeRFs/TorsoNeRF/run_nerf.py --config dataset/$id/TorsoNeRFTest_config.txt --aud_file=${deepspeechfile.npy} --test_size=-1
执行后最后输出的视频是在哪里？

**Comment by aurelianocyp** [comment]
在一个名叫test_aud_rst的文件夹里

**Comment by feifeitu1** [comment]
> 在一个名叫test_aud_rst的文件夹里

好的谢谢，找到了，之前忘记把预模型放到对应的文件夹了

**Comment by piwawa** [comment]
> > 在一个名叫test_aud_rst的文件夹里
> 
> 好的谢谢，找到了，之前忘记把预模型放到对应的文件夹了

预训练模型放哪？
