### ISSUE TITLE
Far scene boundary and background

### ISSUE THREAD

**Issue by RobinRenggli** [YudongGuo/AD-NeRF#15]
I want to know where the z-far and z-near values are used and how this relates to the background image.

I'm asking because I have models of my own and I tried using the poses generated by your model for them. Everything works well, except for the background; in the first few iterations the background image is used (i.e. last sample on ray works) but then the network starts to learn a background anyways. 
I suspect the near/far  boundaries are somehow involved with this, but when I tried looking through the code I couldn't find the z-far value used anywhere. 

Me question is this: How far "back" is the last sample on the ray, where you place the background RGB value? How are the near/far boundaries used? What could lead to the network trying to learn a background even if one is provided?

**Comment by YudongGuo** [comment]
Hi, the near and far parameters are passed to the render_kwargs and then used in the rendering function for sampling.

The near and far valus are the sampling points range along the 'z' axis during volume rendering, and 'z' distance of the last sample to the camera is just 'far' value.

I have no exact idea about your described case. One possible reason is that the head positions in the captured frames cover long ranges in 'z' direction. I think you can set longer ranges for near/far (e.g. near-0.2, far+0.2), or set different near/far values for each frame (currently they share the same near/far) according to the translation parameter in face tracking.

**Comment by RobinRenggli** [comment]
Thank you, I will try this. You can close the issue.

**Comment by RobinRenggli** [comment]
Thank you, I will try this.
