### ISSUE TITLE
Single NeRF Model

### ISSUE THREAD

**Issue by RobinRenggli** [YudongGuo/AD-NeRF#16]
In the video (at the 02:55 mark) you show examples when training with only a single NeRF. I was wondering if you still had that code available, as there are some things I want to try with a single model for the head and torso.

Could you release the model you used before the split into torso nerf and head nerf, or if this is possible with the current code, could you tell me how to do it?

Would it be enough to use orig_imgs instead and change the sample_rate to have the torso appear in the head-nerf?

Thank you in advance.

**Comment by YudongGuo** [comment]
Hi, you are right. The single NeRF can be trained with ori_imgs and proper sample_rect and sample_rate in head-nerf (in our implementation we just set sample_rate to be -1, meaning uniformly sampling in the entire image).

**Comment by RobinRenggli** [comment]
Thank you!

**Comment by Ayiing** [comment]
hi :)  i have the same problem.
so do you know how can i test a single model for the head?

**Comment by RobinRenggli** [comment]
Yes, I created several variations of the models with techniques used in different papers, including a single model version. I'm very busy right now, but once things settle down I will probably release them. 

However, you can probably do this yourself, once you understand how this method works it's very easy to adjust, you only need to change very few lines. "A single model for the head" is not very specific, do you mean with or without the torso in that single model? For most things, you only need to change which images are used to calculate the loss.
