### ISSUE TITLE
After using Obama training, how to change the background and how to drive other target people

### ISSUE THREAD

**Issue by xzkzdx** [YudongGuo/AD-NeRF#17]
After using Obama training, how to change the background and how to drive other target people，do you have more detailed documents.

**Comment by YudongGuo** [comment]
Hi, you can drive the person you trained (e.g. Obama) with another person's audio with the command in README. If you want to drive other people, you need to train on the video of the target person. We plan to give detailed documents and scipts on 
these applications recently.
