### ISSUE TITLE
how long does it take to render?

### ISSUE THREAD

**Issue by xzkzdx** [YudongGuo/AD-NeRF#18]
After the training, how long does it take to render? I have rendered at least one day by professional GPU RTX6000.

**Comment by xzkzdx** [comment]
Dose it support multi GPUs

**Comment by YudongGuo** [comment]
The current implementation doset not support multiple GPUs and I may have no time for this recently. One direct way is to run split time sequences on seperate GPUs in parallel.

**Comment by RobinRenggli** [comment]
I'll just mention that many NeRF models that support multiple GPUs exist. As this repo is at it's core also just a NeRF, it should be easy to combine it with one of these models. 
Keep the per-processing, add the additional inputs to the multi-GPU NeRF, done. 

Many other NeRFs that improve rendering times also exist and their approaches could be applied here.

(I'm not asking Yudong to do this, I'm telling xzkzdx he could do this himself.)
