### ISSUE TITLE
Deepspeech model

### ISSUE THREAD

**Issue by QUTGXX** [YudongGuo/AD-NeRF#20]
Hi Yudong,

I am very interested in your excellent work. When I want to load the deepspeech model ('deepspeech-0.9.2-models.pbmm'), it raised the error ('google.protobuf.message.DecodeError: Error parsing message'). My conda environment is followed your command by 'environment.yml'. Can u help me address this issue?

Best regards,
Allen

**Comment by YudongGuo** [comment]
Hi, we used deepspeech 0.1.0 model ([according to this code](https://github.com/YudongGuo/AD-NeRF/blob/a1dc83f27b6f757069ec27dbd81851a3f027d8d8/data_util/deepspeech_features/deepspeech_store.py#L16)) not the 0.9.2 version.

**Comment by QUTGXX** [comment]
> Hi, we used deepspeech 0.1.0 model ([according to this code](https://github.com/YudongGuo/AD-NeRF/blob/a1dc83f27b6f757069ec27dbd81851a3f027d8d8/data_util/deepspeech_features/deepspeech_store.py#L16)) not the 0.9.2 version.

Thanks for your quick reply. By the way, I have another question.  You mentioned that the deepspeech features will be sent into the 2D convolutional network in the paper, but the code file 'run_nerf_helpers.py' uses the 1D convolutional network. Can u explain more details about this idea?

**Comment by YudongGuo** [comment]
It was an implementation issue. In our original implementation, we applied 2d conv on (n, 29, 16, 1) features. We noticed that it's the same as applying 1d conv on (n, 29, 16), so modified the code accordingly. The 1d conv is ued to aggregate the features along the 'time' axis.

**Comment by QUTGXX** [comment]
> It was an implementation issue. In our original implementation, we applied 2d conv on (n, 29, 16, 1) features. We noticed that it's the same as applying 1d conv on (n, 29, 16), so modified the code accordingly. The 1d conv is ued to aggregate the features along the 'time' axis.

Thanks for your detailed reply. The attention audio net is used for stabilizing the audio signals. Does it improve the audio robustness? Can u tell me more details about this idea?  If this network is without an attention network, whether the face generation will become worse or not?

**Comment by YudongGuo** [comment]
The audio attenton net is used to stabilize the synthesized talking head video. Without the module, the generated video will show obvious jitter especially in the mouth region.

**Comment by QUTGXX** [comment]
> The audio attenton net is used to stabilize the synthesized talking head video. Without the module, the generated video will show obvious jitter especially in the mouth region.

Great! I will try your code later. I truly appreciate your support and explanation.
