### ISSUE TITLE
RuntimeError: The size of tensor a (50) must match the size of tensor b (2) at non-singleton dimension 3

### ISSUE THREAD

**Issue by xiaofeiwu** [YudongGuo/AD-NeRF#21]
Hi,

I met a runtime error when I try to run this code:

File "/home/***/AD-NeRF/data_util/face_tracking/render_3dmm.py", line 75, in forward
    images = softmax_rgb_blend(
  File "/home/***/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 188, in softmax_rgb_blend
    z_inv = (zfar - fragments.zbuf) / (zfar - znear) * mask
RuntimeError: The size of tensor a (50) must match the size of tensor b (2) at non-singleton dimension 3

I use pytorch3d 0.4.0 version.

Is there any information to solve this issue?

**Comment by YudongGuo** [comment]
Hi, this is a bug in old pytorch3d version. You can follow [this instruction](https://github.com/facebookresearch/pytorch3d/issues/652#issue-863403258) to fix it.

**Comment by xiaofeiwu** [comment]
Thanks, it seems that the issue has been resolved.
