### ISSUE TITLE
Inference Time Improvement

### ISSUE THREAD

**Issue by saslamsameja** [YudongGuo/AD-NeRF#22]
Hi @YudongGuo, I understand that the longer inference time is due to the NeRFs. So my question is if we incorporate the updated designs like https://github.com/facebookresearch/DONERF/tree/5aca390d0836d3962c65f359eb57903ac5c68820 which are targeted to achieve real-time inference time of NeRFs, would the inference time of AD-NeRF decrease accordingly.

**Comment by YudongGuo** [comment]
Hi, it's a promising solution to speed up NeRF rendering. But incorporating the designs into AD-NeRF is not trival since almost all of the real-time NeRF designs focus on static scenes, and I didn't find any paper for real-time rendering of conditional NeRFs.

**Comment by saslamsameja** [comment]
> Hi, it's a promising solution to speed up NeRF rendering. But incorporating the designs into AD-NeRF is not trival since almost all of the real-time NeRF designs focus on static scenes, and I didn't find any paper for real-time rendering of conditional NeRFs.

Thanks @YudongGuo for the explanation. Could you please share the NeRF implementation that you used to build the AD-NeRF?

**Comment by YudongGuo** [comment]
Hi, AD-NeRF is implemented based on [nerf-pytorch](https://github.com/yenchenlin/nerf-pytorch).
