### ISSUE TITLE
 coords_norect.shape[0] = 0.

### ISSUE THREAD

**Issue by 649459021** [YudongGuo/AD-NeRF#24]
ValueError
a must be greater than 0 unless no samples are taken
  File "/apdcephfs/private_quincheng/LipSync/AD-NeRF/NeRFs/HeadNeRF/run_nerf.py", line 862, in train
    coords_norect.shape[0], size=[norect_num], replace=False)  # (N_rand,)
  File "/apdcephfs/private_quincheng/LipSync/AD-NeRF/NeRFs/HeadNeRF/run_nerf.py", line 965, in <module>
    train()

I found coords_norect.shape[0] = 0.
How to fix this error?

**Comment by YudongGuo** [comment]
It's because the face rect covers the entire image. You can set sample_rate = -1 in TorsoNeRF_config.txt to avoid the error.

**Comment by 649459021** [comment]
Do you know what could cause this problem?  Is it my video?

**Comment by YudongGuo** [comment]
The reason is that the face rect covers the entire image (the head in your video convers a large region). In this case, setting sample_rate = -1 is ok (meaning uniformly sampling in the whole image), or you can adjust the code to judge such cases.

**Comment by YudongGuo** [comment]
The reason is that the face rect covers the entire image (the head in your video convers a large region). In this case, setting sample_rate = -1 is ok (meaning uniformly sampling in the whole image), or you can adjust the code to judge such cases.

**Comment by 649459021** [comment]
Thanks!  That's a good explanation. 
In addition, can this code use multi-gpus? I try to train my video on one P40 GPU and it will take about 200 hours. The video is only a few seconds long.

**Comment by YudongGuo** [comment]
Currently the code does not support multi-gpus. You can decrease the training iterations (e.g. 40000 iterations). Note that the results may be bad for such a short video (we usually use videos of 3-5 mins).

**Comment by 649459021** [comment]
Thanks
