### ISSUE TITLE
训练时间长的问题

### ISSUE THREAD

**Issue by littlemao54682** [YudongGuo/AD-NeRF#25]
您好，我用Mac电脑，训练 Obama视频，跑了约10个小时，step还没跑完，麻烦问一下，是我训练有问题吗？ 还是就是这么慢的

**Comment by YudongGuo** [comment]
速度主要取决于显卡算力，在3090上跑数据处理大概要2个小时，如果用算力比较低的显卡的话这个时间也是正常的。

**Comment by littlemao54682** [comment]
好的，谢谢
