### ISSUE TITLE
The output video has no sound

### ISSUE THREAD

**Issue by cwchenwang** [YudongGuo/AD-NeRF#27]
Hi, I tried your pre-trained model, but the output video seems to not embedded any sound. I checked out the code and found the VideoWriter didn't write sound or did I miss something?

**Comment by YudongGuo** [comment]
Hi, the generated video doesn't contain audio. You can combine the video with the input audio with some tools like ffmpeg.

**Comment by echoyinke** [comment]
emm, should told us in README
