### ISSUE TITLE
No file 3DMM_info.npy when doing step6 in process_data.py

### ISSUE THREAD

**Issue by sstzal** [YudongGuo/AD-NeRF#28]
Hi, yudong
When I run the process_data.py, there is an error in step 6. Can you tell me where can I find the 3DMM_info.npy?

Here is the details:
Traceback (most recent call last):
  File "data_util/face_tracking/face_tracker.py", line 47, in <module>
    id_dim, exp_dim, tex_dim, point_num)
  File "...../code/AD-NeRF-master/data_util/face_tracking/facemodel.py", line 16, in __init__
    modelpath, '3DMM_info.npy'), allow_pickle=True).item()
  File "..../anaconda3/envs/adnerf_cu11/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '..../code/AD-NeRF-master/data_util/face_tracking/3DMM/3DMM_info.npy'

**Comment by deepSTEM** [comment]
Hello sstzal, have you found out the 01_MorphableModel.mat data file? I search the whole website but still cannot find it. Maybe there is a change happened in that webpage. @sstzal

**Comment by catherine-qian** [comment]
Hi, i also downloaded from https://faces.dmi.unibas.ch/bfm/main.php?nav=1-1-0&id=details while didn't found the .mat.
I receive the email with many links. I downloaded the materials in all links without finding the .mat file.

Could you please kindly share it with me? @sstzal @YudongGuo

**Comment by prajwaljpj** [comment]
@catherine-qian you need to download basel face model **2009**
