### ISSUE TITLE
about canonical space

### ISSUE THREAD

**Issue by 15211** [YudongGuo/AD-NeRF#29]
你好，我对于该方法中，使用pose parameters {R, t} 完成camera space到canonical space的转换这一步感到比较抽象，阅读了论文和参考论文后仍不太理解。请问有什么参考资料可供详细了解和学习吗？

**Comment by YudongGuo** [comment]
你好，由于隐式场mlp的输入为点的坐标，如果直接输入相机坐标系下坐标的话对于同一个点（比如鼻尖的点），该点在不同帧下由于人头姿态{R,t}的影响在相机坐标系下坐标是不一样的，但是同一个点输入mlp坐标应该是一样才合理，所以要根据R，t将点由相机坐标系转到基准坐标系(即把每帧姿态消除)。这里可以类比世界坐标(即基准坐标)和相机坐标的转换，只是换成了假设人头不动，相机在动，然后人头姿态就等价于相机的外参。

**Comment by 15211** [comment]
非常感谢您的工作和解答！

**Comment by cnnAndBn** [comment]
感谢您的工作！ @YudongGuo 
同样对这里有一些疑问,对nerf和人脸3dmm这块是新手，希望得到你的回答！
对于face_tracker.py，我感觉您这里是想利用3DMM模型，通过模型的拟合得到当前训练人的一些关键点的3d坐标点，然后将其投影到图像上，然后再由人脸图像关键点检测模型检测得到的关键点坐标（图像坐标）与3dmm模型投影得到的关键点图像坐标的差作为loss来求3dmm模型的人脸世界坐标到摄像机坐标系（还包括焦距）的旋转和平移矩阵？ 
看了nerf，感觉是物体不动，相机动，但这里通过跟踪可以得到人头部运动（旋转和平移），相当于人在动。这样的话，比如从上往下看，人如果头绕着yaw（朝天上）顺时针旋转一个角度，按照您上边说的，等价于相机绕着该轴从上往下看，逆时针旋转该同样的角度，对吧？如果是这样的话，请问这点体现在了哪里呢？
![image](https://user-images.githubusercontent.com/69999981/189531843-eb84ffdf-9dc4-4ce1-9b98-a69b2c484875.png)

还有一个问题就是，上边说canonical space和摄像机坐标系之间的转换，我看代码， https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/HeadNeRF/run_nerf.py#L321
，这里是false，并没有用NDC坐标系把？

**Comment by YudongGuo** [comment]
> 感谢您的工作！ @YudongGuo 同样对这里有一些疑问,对nerf和人脸3dmm这块是新手，希望得到你的回答！ 对于face_tracker.py，我感觉您这里是想利用3DMM模型，通过模型的拟合得到当前训练人的一些关键点的3d坐标点，然后将其投影到图像上，然后再由人脸图像关键点检测模型检测得到的关键点坐标（图像坐标）与3dmm模型投影得到的关键点图像坐标的差作为loss来求3dmm模型的人脸世界坐标到摄像机坐标系（还包括焦距）的旋转和平移矩阵？ 看了nerf，感觉是物体不动，相机动，但这里通过跟踪可以得到人头部运动（旋转和平移），相当于人在动。这样的话，比如从上往下看，人如果头绕着yaw（朝天上）顺时针旋转一个角度，按照您上边说的，等价于相机绕着该轴从上往下看，逆时针旋转该同样的角度，对吧？如果是这样的话，请问这点体现在了哪里呢？ ![image](https://user-images.githubusercontent.com/69999981/189531843-eb84ffdf-9dc4-4ce1-9b98-a69b2c484875.png)
> 
> 还有一个问题就是，上边说canonical space和摄像机坐标系之间的转换，我看代码，
> 
> https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/HeadNeRF/run_nerf.py#L321
> 
> 
> ，这里是false，并没有用NDC坐标系把？

你好,

**Comment by YudongGuo** [comment]
> 感谢您的工作！ @YudongGuo 同样对这里有一些疑问,对nerf和人脸3dmm这块是新手，希望得到你的回答！ 对于face_tracker.py，我感觉您这里是想利用3DMM模型，通过模型的拟合得到当前训练人的一些关键点的3d坐标点，然后将其投影到图像上，然后再由人脸图像关键点检测模型检测得到的关键点坐标（图像坐标）与3dmm模型投影得到的关键点图像坐标的差作为loss来求3dmm模型的人脸世界坐标到摄像机坐标系（还包括焦距）的旋转和平移矩阵？ 看了nerf，感觉是物体不动，相机动，但这里通过跟踪可以得到人头部运动（旋转和平移），相当于人在动。这样的话，比如从上往下看，人如果头绕着yaw（朝天上）顺时针旋转一个角度，按照您上边说的，等价于相机绕着该轴从上往下看，逆时针旋转该同样的角度，对吧？如果是这样的话，请问这点体现在了哪里呢？ ![image](https://user-images.githubusercontent.com/69999981/189531843-eb84ffdf-9dc4-4ce1-9b98-a69b2c484875.png)
> 
> 还有一个问题就是，上边说canonical space和摄像机坐标系之间的转换，我看代码，
> 
> https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/HeadNeRF/run_nerf.py#L321
> 
> 
> ，这里是false，并没有用NDC坐标系把？

你好,
设3dmm的坐标系到世界坐标系变换是T_h2w,世界坐标系到相机坐标系变换是T_w2c.则3dmm坐标系到相机坐标系的复合变换是T_w2c*T_h2w.
如果相机不动人动,则T_w2c是固定的而T_h2w是随着头部pose变化的.  如果相机动人不动,则相反.  从最终成像结果来看,假设头部是刚性的话这两种情况可以互相转换,只要复合矩阵一致即可.

**Comment by cnnAndBn** [comment]
非常感谢！请问最开始是假设3dmm的坐标系和世界坐标系重合吗？

**Comment by YudongGuo** [comment]
是的，实现里认为是重合的
