### ISSUE TITLE
Torso not added to final output

### ISSUE THREAD

**Issue by RobinRenggli** [YudongGuo/AD-NeRF#3]
I trained the Obama example and I get expected results from the HeadNeRF, but when I train and render the TorsoNeRF, I get results that look very similar (i.e. a floating head, torso is missing). I only trained for 10'000 iterations, but from my experience with NeRF, the correct shapes should appear rather quickly. 

Could it be that there is a setting that needs to be turned on, or a bug in the code, that prevents the Torso from being learned by the TorsoNeRF? Or does it take a large amount of iterations for the Torso to appear?

I used the commands as specified in the README.

Thanks for your help, this is a very cool project!

HeadNeRF output:
![000](https://user-images.githubusercontent.com/32697212/123509640-e61bd200-d676-11eb-838e-e0aeed5bab0c.png)
TorsoNeRF output:
![000](https://user-images.githubusercontent.com/32697212/123509641-eae08600-d676-11eb-8248-4f901cebfb4c.jpg)

**Comment by YudongGuo** [comment]
Hi, actually it's a problem of network initialization. We found that in few cases the torso model could not produce proper output due to bad initialization.

One solution is to run the command multiple times until good initialization (in my experience, the psnr is greater than 21 in 1000 iterations for a good initialization). Another solution is to use a pretrained Torso model (e.g. torso model trained from another person).

**Comment by RobinRenggli** [comment]
Oh, ok, this is really useful to know. I see now that in my run PSNR was still below 20 after 10'000 iterations. 

Thanks for your help.

**Comment by RobinRenggli** [comment]
I tried several times now with multiple attempts with PSNR over 25 and different input videos and it never worked. Could you maybe provide a pretrained torso model such that I can try if that makes it work/look at how the results are supposed to look? 
(The HeadNeRF works very well!)

**Comment by YudongGuo** [comment]
Hi, the Torso model pretrained on the obama video is here:
https://www.dropbox.com/s/hy99o8jm3iyskur/500000_body.tar?dl=0 

It should work.

**Comment by RobinRenggli** [comment]
Thank you, I'll try it out today.

**Comment by RobinRenggli** [comment]
I can confirm that it works by using a pretrained torso model, even if the torso in question is very different from the pretrained one. 

In my example, I could not get a good initialization even after many tries. Do you maybe have an intuition or explanation on how likely/unlikely a good initialization is? Does it depend on how much of the frame is taken up by the torso?

Feel free to close this issue, as my question is more of a research one.

**Comment by yuzhou164** [comment]
Ask a question！ When I use the model provided by the author for training Torso, the model can not be trained? Do you handle with this problem?

**Comment by YudongGuo** [comment]
> I can confirm that it works by using a pretrained torso model, even if the torso in question is very different from the pretrained one.
> 
> In my example, I could not get a good initialization even after many tries. Do you maybe have an intuition or explanation on how likely/unlikely a good initialization is? Does it depend on how much of the frame is taken up by the torso?
> 
> Feel free to close this issue, as my question is more of a research one.

Hi, in my experience, I can get a good initialization with a single attempt in most cases. In all cases, a good initialization is achieved with no more than 5 attempts. 

For bad initialization, the PSNR does not show obvious improvement (usually below 20). For good initialization, the PSNR shows obvious improvement in the first 1000 iterations and usually above 21. I didn't notice the correlation with the torso part rate.

It's strange that you didn't get proper results even with PSNR greater than 25. However, you can always use the pretrained torso model for initialization.

**Comment by saslamsameja** [comment]
Hi @YudongGuo, What is the expected value of PSNR for the training of HeadNeRF? I started a training iteration and completed about 200k iterations but my PSNR value is still at around 19. I used all default settings and commands given in Readme.

**Comment by YudongGuo** [comment]
> Hi @YudongGuo, What is the expected value of PSNR for the training of HeadNeRF? I started a training iteration and completed about 200k iterations but my PSNR value is still at around 19. I used all default settings and commands given in Readme.

Hi, expected PSNR is over 30. And in rare cases (with lower rate than TorsoNeRF) HeadNeRF suffers from bad initialiation too. So the advices for training TorsoNeRF above also apply to HeadNeRF.

**Comment by saslamsameja** [comment]
> > Hi @YudongGuo, What is the expected value of PSNR for the training of HeadNeRF? I started a training iteration and completed about 200k iterations but my PSNR value is still at around 19. I used all default settings and commands given in Readme.
> 
> Hi, expected PSNR is over 30. And in rare cases (with lower rate than TorsoNeRF) HeadNeRF suffers from bad initialization too. So the advices for training TorsoNeRF above also apply to HeadNeRF.

@YudongGuo, could you please provide the HeadNerf pre-trained weights for the Obama video as well?

**Comment by YudongGuo** [comment]
Hi, I have uploaded both pretrained models in pretrained_models/ folder. Note that the code of face tracking for training the uploaded models is slightly different from this repo.

**Comment by saslamsameja** [comment]
Thanks, @YudongGuo. I have two questions:
- Even though the code for face tracking is different but using these weights for initialization will fix the problem of training, right?
- And do you plan on publishing the changes related to the face tracking as well?

**Comment by saslamsameja** [comment]
I got a PSNR of around 30 on the 2nd iteration of HeadNerf training, without loading the pre-trained weights. Thanks, @YudongGuo.

**Comment by YudongGuo** [comment]
> Thanks, @YudongGuo. I have two questions:
> 
> * Even though the code for face tracking is different but using these weights for initialization will fix the problem of training, right?
> * And do you plan on publishing the changes related to the face tracking as well?

Hi, the weights could be used for good initialization. And there were slight differences in differentiable rendering settings and tracking smoothness settings (in general the tracking code in this repo is better).

**Comment by saslamsameja** [comment]
https://user-images.githubusercontent.com/32391022/124060224-061c0e80-da46-11eb-9976-10f5faf7d8a3.mp4

@YudongGuo, the output that I generated using the weights that you shared has a lot of flickering between the head and torso. Could this be due to the difference in the tracking code that you mentioned? Or is there any other reason for this. Because I noticed that the demos that you shared do not have this noise.

**Comment by YudongGuo** [comment]
>  adnerfsub.mp4 
> @YudongGuo, the output that I generated using the weights that you shared has a lot of flickering between the head and torso. Could this be due to the difference in the tracking code that you mentioned? Or is there any other reason for this. Because I noticed that the demos that you shared do not have this noise.

I thinks it's because the difference between the tracking parameters. You can finetune the models with current parameters, and I will check this part too.

**Comment by YudongGuo** [comment]
>  adnerfsub.mp4 
> @YudongGuo, the output that I generated using the weights that you shared has a lot of flickering between the head and torso. Could this be due to the difference in the tracking code that you mentioned? Or is there any other reason for this. Because I noticed that the demos that you shared do not have this noise.


https://user-images.githubusercontent.com/28282620/124066790-e4358280-da6b-11eb-8b23-9ec64a8fce22.mp4

Hi, this is the generated video with the tracking parameters (attached) of pretrained models. So it's because the inconsistence between tracking parameters.
[transforms_train.txt](https://github.com/YudongGuo/AD-NeRF/files/6745566/transforms_train.txt)
[TorsoNeRFTest_config.txt](https://github.com/YudongGuo/AD-NeRF/files/6745567/TorsoNeRFTest_config.txt)

**Comment by kingsj0405** [comment]
I also got the same problem with another identity.
Both trainings from scratch and from Obama are tried.
Can I get any advice to converge?

![image](https://user-images.githubusercontent.com/13496612/185779311-09e07790-f313-4546-b81c-4266b3120f6a.png)
