### ISSUE TITLE
Problem about loading the torso pretrained models 

### ISSUE THREAD

**Issue by sstzal** [YudongGuo/AD-NeRF#30]
Hi, yudong
When I try to load the torso pretrained models for a better initialization. I get an error.
![image](https://user-images.githubusercontent.com/40749976/131644660-f66a5682-d256-41eb-a195-a0f0fdfdac68.png)
So why the pretrained models donot have the ['network_audattnet_state_dict']. How can I handle this issue?
Thanks!

**Comment by sstzal** [comment]
> Hi, yudong
> When I try to load the torso pretrained models for a better initialization. I get an error.
> ![image](https://user-images.githubusercontent.com/40749976/131644660-f66a5682-d256-41eb-a195-a0f0fdfdac68.png)
> So why the pretrained models donot have the ['network_audattnet_state_dict']. How can I handle this issue?
> Thanks!

Should I set the 'with_audatt' to be False?

**Comment by YudongGuo** [comment]
> > Hi, yudong
> > When I try to load the torso pretrained models for a better initialization. I get an error.
> > ![image](https://user-images.githubusercontent.com/40749976/131644660-f66a5682-d256-41eb-a195-a0f0fdfdac68.png)
> > So why the pretrained models donot have the ['network_audattnet_state_dict']. How can I handle this issue?
> > Thanks!
> 
> Should I set the 'with_audatt' to be False?

Yep. The reason is that the torso model shares the AudioAttention module with the head model, so there is no need to load it again.

**Comment by YudongGuo** [comment]
> > > Hi, yudong
> > > When I try to load the torso pretrained models for a better initialization. I get an error.
> > > ![image](https://user-images.githubusercontent.com/40749976/131644660-f66a5682-d256-41eb-a195-a0f0fdfdac68.png)
> > > So why the pretrained models donot have the ['network_audattnet_state_dict']. How can I handle this issue?
> > > Thanks!
> > 
> > 
> > Should I set the 'with_audatt' to be False?
> 
> Yep. The reason is that the torso model shares the AudioAttention module with the head model, so there is no need to load it again.

From your output, the head model does not contain the audattnet, didn't you include it in the head model training?

**Comment by sstzal** [comment]
> > > > Hi, yudong
> > > > When I try to load the torso pretrained models for a better initialization. I get an error.
> > > > ![image](https://user-images.githubusercontent.com/40749976/131644660-f66a5682-d256-41eb-a195-a0f0fdfdac68.png)
> > > > So why the pretrained models donot have the ['network_audattnet_state_dict']. How can I handle this issue?
> > > > Thanks!
> > > 
> > > 
> > > Should I set the 'with_audatt' to be False?
> > 
> > 
> > Yep. The reason is that the torso model shares the AudioAttention module with the head model, so there is no need to load it again.
> 
> From your output, the head model does not contain the audattnet, didn't you include it in the head model training?

I have audattnet in the headnerf. I

**Comment by YudongGuo** [comment]
You can just put your trained head model and the pretrained torso model in the torso checkpoint folder (dataset/$id/logs/$id_com by default). You also need to manually adjust the 'global_step' in line 789 to 0.

**Comment by sstzal** [comment]
I find the torso model has these keys:
![image](https://user-images.githubusercontent.com/40749976/131648756-b613365f-0ef4-495a-b947-abe2dd4d6c42.png)
and the head model has these:
![image](https://user-images.githubusercontent.com/40749976/131648796-329faf07-be6b-45c8-9a79-5e92edc2bdfc.png)

So when I train the torso nerf model , shoule I load 
![image](https://user-images.githubusercontent.com/40749976/131649007-8697e58d-b635-4f9f-ad29-bf3428ad2676.png)
from troso model and 
![image](https://user-images.githubusercontent.com/40749976/131649180-08efcfa4-1953-4231-a481-db6fc94d5ce2.png)
from head model?

**Comment by sstzal** [comment]
> You can just put your trained head model and the pretrained torso model in the torso checkpoint folder (dataset/$id/logs/$id_com by default). You also need to manually adjust the 'global_step' in line 789 to 0.

![image](https://user-images.githubusercontent.com/40749976/131649422-9f91b276-d962-485c-a232-10ca4f592a9d.png)
I read the code. And I think if i put these two model in the dataset/$id/logs/$id_com. The code will only load one model since ckpt_path = ckpts[-1]. Can you tell me what's wrong with my understanding?

**Comment by YudongGuo** [comment]
> > You can just put your trained head model and the pretrained torso model in the torso checkpoint folder (dataset/$id/logs/$id_com by default). You also need to manually adjust the 'global_step' in line 789 to 0.
> 
> ![image](https://user-images.githubusercontent.com/40749976/131649422-9f91b276-d962-485c-a232-10ca4f592a9d.png)
> I read the code. And I think if i put these two model in the dataset/$id/logs/$id_com. The code will only load one model since ckpt_path = ckpts[-1]. Can you tell me what's wrong with my understanding?

In the code [here](https://github.com/YudongGuo/AD-NeRF/blob/a1dc83f27b6f757069ec27dbd81851a3f027d8d8/NeRFs/TorsoNeRF/run_nerf.py#L336), it only searches the file containing specific substring ('head' or 'torso').

**Comment by sstzal** [comment]
I get it! Thanks!
