### ISSUE TITLE
关于DeepSpeech提取的特征问题？

### ISSUE THREAD

**Issue by liushao** [YudongGuo/AD-NeRF#32]
您好，我下载使用deepspeech-0_1_0-b90017e8.pb.zip，但是针对obama的语音提取得到的aud.npy与您提供的Obama_test环境中的aud.npy不一样，请问是什么原因？程序没有做任何的改动，非常感谢

**Comment by YudongGuo** [comment]
您好，我测试了一下确实跟obama_test中提供的不一样，不确定是哪儿的问题，可能是之前代码有过修改，你可以尝试用生成的文件训练下，效果应该差不多。

**Comment by liushao** [comment]
> 您好，我测试了一下确实跟obama_test中提供的不一样，不确定是哪儿的问题，可能是之前代码有过修改，你可以尝试用生成的文件训练下，效果应该差不多。

好的，我试试，谢谢哈

**Comment by liushao** [comment]
> 您好，我测试了一下确实跟obama_test中提供的不一样，不确定是哪儿的问题，可能是之前代码有过修改，你可以尝试用生成的文件训练下，效果应该差不多。

您好，我用新声场的Obama的音频进行训练，再用音频推理时确实头和身体不分离，但是再用其他的音频推理还是有严重的头身分离现象。请问可能是哪一个环节有异常了？

**Comment by YudongGuo** [comment]
> > 您好，我测试了一下确实跟obama_test中提供的不一样，不确定是哪儿的问题，可能是之前代码有过修改，你可以尝试用生成的文件训练下，效果应该差不多。
> 
> 您好，我用新生成的Obama的音频进行训练，再用音频推理时确实头和身体不分离，但是再用其他的音频推理还是有严重的头身分离现象。请问可能是哪一个环节有异常了？对音频本身还有什么特殊要求吗？

您好，对音频本身没有特殊要求，不过最好测试和训练的语言一致。一个可能的原因是模型训练迭代次数不够多，可以多训练一下看看效果。

**Comment by liushao** [comment]
> 您好，对音频本身没有特殊要求，不过最好测试和训练的语言一致。一个可能的原因是模型训练迭代次数不够多，可以多训练一下看看效果。

语音都用的英文，body在预训练模型上初始化的基础上迭代到了600000次，问题依然存在。

**Comment by YudongGuo** [comment]
> > 您好，对音频本身没有特殊要求，不过最好测试和训练的语言一致。一个可能的原因是模型训练迭代次数不够多，可以多训练一下看看效果。
> 
> 语音都用的英文，body在预训练模型上初始化的基础上迭代到了600000次，问题依然存在。

Hi，我基于现在的代码（调整了下学习速率）重新训练了下，head迭代300000次，body迭代600000次，更新到[pretrained_models](https://github.com/YudongGuo/AD-NeRF/tree/master/pretrained_models)下，我用其他人音频测试头部身体连接处没有很明显的分离，你可以测试一下试试。

**Comment by liushao** [comment]
> Hi，我基于现在的代码（调整了下学习速率）重新训练了下，head迭代300000次，body迭代600000次，更新到[pretrained_models](https://github.com/YudongGuo/AD-NeRF/tree/master/pretrained_models)下，我用其他人音频测试头部身体连接处没有很明显的分离，你可以测试一下试试。
好的，我来验证一下，另外，可以分享一下您的学习率调整值吗？请问训练初始化是随机还是用之前的预训练结果？

**Comment by YudongGuo** [comment]
> > Hi，我基于现在的代码（调整了下学习速率）重新训练了下，head迭代300000次，body迭代600000次，更新到[pretrained_models](https://github.com/YudongGuo/AD-NeRF/tree/master/pretrained_models)下，我用其他人音频测试头部身体连接处没有很明显的分离，你可以测试一下试试。
> > 好的，我来验证一下，另外，可以分享一下您的学习率调整值吗？请问训练初始化是随机还是用之前的预训练结果？

就是现在版本代码里默认的设置，是随机初始化训练的。

**Comment by liushao** [comment]
> Hi，我基于现在的代码（调整了下学习速率）重新训练了下，head迭代300000次，body迭代600000次，更新到[pretrained_models](https://github.com/YudongGuo/AD-NeRF/tree/master/pretrained_models)下，我用其他人音频测试头部身体连接处没有很明显的分离，你可以测试一下试试。

验证了，确实比我自己训练的效果好，头身分离现象大幅改善，只有个别帧会存在。

**Comment by loongofqiao** [comment]
> > > Hi，我基于现在的代码（调整了下学习速率）重新训练了下，head迭代300000次，body迭代600000次，更新到[pretrained_models](https://github.com/YudongGuo/AD-NeRF/tree/master/pretrained_models)下，我用其他人音频测试头部身体连接处没有很明显的分离，你可以测试一下试试。
> > > 好的，我来验证一下，另外，可以分享一下您的学习率调整值吗？请问训练初始化是随机还是用之前的预训练结果？
> 
> 就是现在版本代码里默认的设置，是随机初始化训练的。

你好，训练body的过程中，存在头和身体分离的情况，随着迭代的增加，这个问题会消失吗
