### ISSUE TITLE
关于测试视频

### ISSUE THREAD

**Issue by GaryGky** [YudongGuo/AD-NeRF#33]
您好，请问除了Obama的视频之外，能否提供一下paper中其他视频的连接？

**Comment by GaryGky** [comment]
想再补充一个问题，请问您是否尝试过使用DataParallel对模型进行加速训练？目前我使用DP封装了已有的Network，PSNR值只能到达27~28附近，与paper的渲染效果（PSNR=33~34）差的有点大。

**Comment by YudongGuo** [comment]
您好，我们用到的一些视频链接如下：

https://www.youtube.com/watch?v=_0k_YwBm_NE&t=289s
https://www.tagesschau.de/multimedia/video/video-494929.html
https://www.tagesschau.de/multimedia/video/video-521293.html

**Comment by DaddyJin** [comment]
您好，麻烦问一下，请问您们在预处理视频的时候使用了怎样的截取策略呢，就是按照什么逻辑截取的人脸和衣着部分？
十分感谢！ @YudongGuo

**Comment by GaryGky** [comment]
> 您好，我们用到的一些视频链接如下：
> 
> https://www.youtube.com/watch?v=_0k_YwBm_NE&t=289s
> https://www.tagesschau.de/multimedia/video/video-494929.html
> https://www.tagesschau.de/multimedia/video/video-521293.html

谢谢~

**Comment by YudongGuo** [comment]
> 您好，麻烦问一下，请问您们在预处理视频的时候使用了怎样的截取策略呢，就是按照什么逻辑截取的人脸和衣着部分？
> 十分感谢！ @YudongGuo

您好，我们用的开源的人脸分割模型[face-parsing.PyTorch](https://github.com/zllrunning/face-parsing.PyTorch)来分割人脸和身体部分，因为这两部分刚性运动不一致，所以用两个模块分别处理。

**Comment by catherine-qian** [comment]
@YudongGuo , 您好，请问
1. 第一个视频https://www.youtube.com/watch?v=_0k_YwBm_NE&t=289s用的part是哪一部分呢？
2. 文章中Tab1提到的 testsetA和testsetB 请问具体是哪些video呢?
3. 因为从table1的结果来说(syncnet score & AU error), the proposed method 的数值并不是最好的，文章中也没有提及？ 

期待您的解答！

**Comment by e4s2022** [comment]
How did you crop the raw videos to 450x450?
