### ISSUE TITLE
About video_fps

### ISSUE THREAD

**Issue by urnotpopcorn** [YudongGuo/AD-NeRF#34]
Great work! And I notice that you set video_fps=50 in deepspeech_features.py. If the input video is 30fps, do I need to adjust this parameter? Or is there anything I should change?

**Comment by YudongGuo** [comment]
Hi, you should adjust the video to be 25fps (using tools like adobe premiere or ffmpeg) and put it to dataset/vids/$id.mp4. Then just follow the commands in this repo.

**Comment by urnotpopcorn** [comment]
> Hi, you should adjust the video to be 25fps (using tools like adobe premiere or ffmpeg) and put it to dataset/vids/$id.mp4. Then just follow the commands in this repo.

thanks

**Comment by lsvagusa** [comment]
Why exactly does the input video need to be 25FPS, could other framerates work and if yes how?
