### ISSUE TITLE
About camera intrinsics

### ISSUE THREAD

**Issue by Tara8573** [YudongGuo/AD-NeRF#39]
请问用process_data.py可以获取camera intrinsics吗？

**Comment by l-mengwei** [comment]
> We assume the priciple point is the center of the image, and estimate the focal length [here](https://github.com/YudongGuo/AD-NeRF/blob/14ad9835135a6b92491f47c5fd2e36e7174ef7d0/data_util/face_tracking/face_tracker.py#L57).

请问，face_tracker.py中的arg_focal=1600是如何确定的？这个focal是假设的吗？有什么依据吗？期待您的回复，谢谢～

**Comment by YudongGuo** [comment]
> > We assume the priciple point is the center of the image, and estimate the focal length [here](https://github.com/YudongGuo/AD-NeRF/blob/14ad9835135a6b92491f47c5fd2e36e7174ef7d0/data_util/face_tracking/face_tracker.py#L57).
> 
> 请问，face_tracker.py中的arg_focal=1600是如何确定的？这个focal是假设的吗？有什么依据吗？期待您的回复，谢谢～

1600是初始值，后面的代码会在600-1500之间搜寻使得关键点误差最小的焦距作为最终焦距

**Comment by mortal-Zero** [comment]
> > > We assume the priciple point is the center of the image, and estimate the focal length [here](https://github.com/YudongGuo/AD-NeRF/blob/14ad9835135a6b92491f47c5fd2e36e7174ef7d0/data_util/face_tracking/face_tracker.py#L57).
> > 
> > 
> > 请问，face_tracker.py中的arg_focal=1600是如何确定的？这个focal是假设的吗？有什么依据吗？期待您的回复，谢谢～
> 
> 1600是初始值，后面的代码会在600-1500之间搜寻使得关键点误差最小的焦距作为最终焦距

Excuse me, why do you need to find the best focal length between 600 and 1500?
Looking forward to your reply.
