### ISSUE TITLE
pytorch3d

### ISSUE THREAD

**Issue by wode123** [YudongGuo/AD-NeRF#4]
Hello, mine is RTX3090, now the installation of pytorch3d error, the problem can not install nvidiacub, I custom installation can not be called, this place how do you solve?

**Comment by YudongGuo** [comment]
Hi, my environment is also 3090 with cuda version 11.2. I recommend the same cuda version and follow the steps in 'Prerequisites' part (make sure install from a local clone for pytorch3d) in a clean conda environment.

**Comment by wode123** [comment]
After downloading this
curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
tar xzf 1.10.0.tar.gz
export CUB_HOME=$PWD/cub-1.10.0
I don't know how to set it up “set before building as described above.rm -rf build/ **/*.sopip install -e .CUB_HOME”

**Comment by wode123** [comment]
Can you give me a detailed installation instruction for the environment? Pytorch3d in particular

**Comment by YudongGuo** [comment]
Hi, I installed the required packages for building pytorch3d via conda:

conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub

Then built pytorch3d from a local clone.

**Comment by wode123** [comment]
Hi,I installed it the same way, but in the second step, run to the general, there is a cuda error: no kernel images is available for execution on the the device problem, I suspect it is pytorch3d nvidiacub installation problem, torch cuda support ,so

**Comment by GzuPark** [comment]
@wode123 Well, I recommend to set up nvidia-docker environment in this case. Base docker image `nvcr.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04` will be fine. And just follow prerequisite step in this repo.

**Comment by wode123** [comment]
Thank you very much for your valuable advice, my problem solved

**Comment by wode123** [comment]
> @wode123 Well, I recommend to set up nvidia-docker environment in this case. Base docker image `nvcr.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04` will be fine. And just follow prerequisite step in this repo.

Thank you, your suggestion is very valuable, we are trying docker

**Comment by GzuPark** [comment]
@wode123 your welcome.
How about share your dockerfile to @YudongGuo if your team agree?
I can share mine, but it takes time for arranging.

**Comment by YudongGuo** [comment]
> @wode123 your welcome.
> How about share your dockerfile to @YudongGuo if your team agree?
> I can share mine, but it takes time for arranging.

Hi, thank both of you! It would be great for sharing it.

**Comment by ZziTaiLeo** [comment]
> 

Hi! I got errors like this. I just do like what you said. My environment is also 3090 with cuda version 11.4, but cudatoolkit is 11.1 
 in conda environment.
![image](https://user-images.githubusercontent.com/42994566/186433391-752ebc2b-fec1-40dc-92d9-b303426c6a82.png)


> Hi, I installed the required packages for building pytorch3d via conda:
> 
> conda install -c fvcore -c iopath -c conda-forge fvcore iopath conda install -c bottler nvidiacub
> 
> Then built pytorch3d from a local clone.
