### ISSUE TITLE
Сontinue training

### ISSUE THREAD

**Issue by shiron8bit** [YudongGuo/AD-NeRF#41]
Hello, 
what is the best option to continue training (after default 400k iters, for example)? And would it be useful at all? (in cases where trained model  does not provide any noticeable mouth movement).

**Comment by shiron8bit** [comment]
up this issue hoping to get answer

**Comment by YudongGuo** [comment]
Hi, I think continue training will not help if the model does not provide any noticeable mouth movement. It may be the problem of initialization, did you try to retrain the model, or did you check that the training video was properly processed (the video should be 25fps and should be synchronized with the audio).
