### ISSUE TITLE
arguments of pre-trained model

### ISSUE THREAD

**Issue by jihyeonRyu** [YudongGuo/AD-NeRF#42]
Hello, 
Is there any arguments guid for pre-trained model??
I got error when I run script  on default setting.

> python NeRFs/TorsoNeRF/run_nerf.py --config dataset/Obama/TorsoNeRFTest_config.txt --aud_file=dataset/Obama/aud.npy --test_size=300 --ft_path ./pretrained_models/600000_body.tar

```
RuntimeError: Error(s) in loading state_dict for FaceNeRF:
        size mismatch for pts_linears.0.weight: copying a param with shape torch.Size([256, 169]) from checkpoint, the shape in current model is torch.Size([256, 127]).
        size mismatch for pts_linears.5.weight: copying a param with shape torch.Size([256, 425]) from checkpoint, the shape in current model is torch.Size([256, 383]).
```

**Comment by ZziTaiLeo** [comment]
> I changed ckpt loading code on create_nerf() at NeRFs/TorsoNeRF/run_nerf.py
> 
> ```
>     if args.ft_path is not None and args.ft_path != 'None':
>         import glob
>         ckpts = sorted(glob.glob(f"{args.ft_path}/*.tar"))
>         ckpts = [ ckpt for ckpt in ckpts if ext in ckpt]
> ```

Hi! Did you retrain two Nerfs with Obama.mp4?  I loaded pretrained model but it still mismatch size.

**Comment by ZziTaiLeo** [comment]
> > I changed ckpt loading code on create_nerf() at NeRFs/TorsoNeRF/run_nerf.py
> > ```
> >     if args.ft_path is not None and args.ft_path != 'None':
> >         import glob
> >         ckpts = sorted(glob.glob(f"{args.ft_path}/*.tar"))
> >         ckpts = [ ckpt for ckpt in ckpts if ext in ckpt]
> > ```
> 
> Hi! Did you retrain two Nerfs with Obama.mp4? I loaded pretrained model but it still mismatch size.



> I changed ckpt loading code on create_nerf() at NeRFs/TorsoNeRF/run_nerf.py
> 
> ```
>     if args.ft_path is not None and args.ft_path != 'None':
>         import glob
>         ckpts = sorted(glob.glob(f"{args.ft_path}/*.tar"))
>         ckpts = [ ckpt for ckpt in ckpts if ext in ckpt]
> ```

I got the solution， thanks you！
