### ISSUE TITLE
Head and lip movement in output video stops after 29 seconds

### ISSUE THREAD

**Issue by neuronx1** [YudongGuo/AD-NeRF#44]
Hello,
thanks for your great work.
I have some problems at inferencing time.
My output video (attached) has no lip movement and headmovement after 29 seconds.
What have I done wrong and how can I solve the problem?
I used your pretrained checkpoints.

https://user-images.githubusercontent.com/62887153/139653059-f14dde34-ae35-4593-bc2c-52279ebd5367.mp4

**Comment by YudongGuo** [comment]
Hi, you should change the test_size to -1.

**Comment by neuronx1** [comment]
> 
> 
> Hi, you should change the test_size to -1.

Hi @YudongGuo,

thanks for yor response.
Actually I generated the above video with the following command:

`
python NeRFs/TorsoNeRF/run_nerf.py --config dataset/Obama/TorsoNeRFTest_config.txt --aud_file=dataset/short_extra_sv_final_a/aud_short.npy --test_size=-1
`

The test_size should already be -1.
Do I have to change the test_size anywhere else?

What have I done wrong?

**Comment by YudongGuo** [comment]
Hi, changing to 'test_pose_file = transforms_train.json' in the config file may solve your problem.

**Comment by neuronx1** [comment]
> 
> 
> Hi, changing to 'test_pose_file = transforms_train.json' in the config file may solve your problem.

Hi @YudongGuo ,
thanks you very much.
Now everything works perfect!
