### ISSUE TITLE
TorsoNeRF_config.txt, TorsoNeRFTest_config.txt files are not exist. 

### ISSUE THREAD

**Issue by muxiddin19** [YudongGuo/AD-NeRF#46]
Can you please share these files?

**Comment by wang-zm18** [comment]
hello, Have you gotten two config files?

**Comment by muxiddin19** [comment]
[TorsoNeRFTest_config.txt](https://github.com/YudongGuo/AD-NeRF/files/7502972/TorsoNeRFTest_config.txt)

**Comment by wang-zm18** [comment]
Got it! Thank you!

muxiddin19 ***@***.***> 于2021年11月9日周二 下午4:04写道：
