### ISSUE TITLE
How to improve 3d pose results?

### ISSUE THREAD

**Issue by unoShin** [YudongGuo/AD-NeRF#49]
Hi 
Thanks for your great work.

I trained AD-NeRF with custom training dataset.
But I have problems with tracking parameters so the rendering results have flickering on torso.
(I trained with your pretrained nerf models)
I found that training with your pretrained parameters showed good results.
Is there any good way to improve tracking parameters by face_tracker.py for better torso and neck part?
Usually head nerf model is trained well but torso model fails to train.

![image](https://user-images.githubusercontent.com/26159308/140879689-f5c11683-8aa8-420d-8d98-dc33d1fbf124.png)

**Comment by YudongGuo** [comment]
Hi, the algorithm in the paper doesn't support the rendering of largely moving torso part. One possible solution is to estimate the torso pose explicitly, either by NeRF rendering or other methods. You may refer to some self bundle-adjustment NeRF papers, e.g. [BARF](https://chenhsuanlin.bitbucket.io/bundle-adjusting-NeRF/), [NeRF--](https://nerfmm.active.vision/).
