### ISSUE TITLE
请问3DMM重建用到的是什么模型？

### ISSUE THREAD

**Issue by 821029883** [YudongGuo/AD-NeRF#5]
作者您好，感谢您开源出色的工作。
有相关问题想请教您：
1.留意到在data_util/face_tracking.py 中有涉及到对3DMM 参数的重建，想请问下 这个3DMM参数重建使用的是什么模型呢？(RingNet、微软那篇或者DECA等？)
2.我按照您的数据预处理方式处理了Obama的视频，目前在训练Obama_head的阶段，我发现迭代300000次非常的耗时间(这可能与NeRF本身训练有关)，可否加速训练？
感谢您出色的工作，期待您的答复，谢谢！

**Comment by YudongGuo** [comment]
您好，
1. 我们用的人脸模型身份部分是BFM 2009，表情部分是我们[另一个工作](https://github.com/Juyong/3DFace)中使用facewarehouse数据构造的表情基，重建部分是利用pytorch3d里可微渲染来优化3dmm及姿态参数。
2. 时间是由于nerf本身体渲染过程采样比较耗时，可以考虑通过引入一些加速策略，如[NSVF](https://github.com/facebookresearch/NSVF)等。

**Comment by 821029883** [comment]
感谢您的解答，它对我帮助很大
