### ISSUE TITLE
where is the "track_params.pt"?

### ISSUE THREAD

**Issue by wang-zm18** [YudongGuo/AD-NeRF#51]
Hello when I run the process_data.py， the error occurs as "No such file or directory: 'dataset/Obama/track_params.pt' ". Could you tell me how I can get this file? Thank you in advance!

**Comment by YudongGuo** [comment]
Hi, the file is generated by step 6 in process data. You may check whether this step succeeded.

**Comment by wang-zm18** [comment]
OK, thank you for your advice!

YudongGuo ***@***.***> 于2021年11月10日周三 下午6:23写道：

**Comment by shaoshengsong** [comment]
https://flyfish.blog.csdn.net/article/details/121979096
His cloud disk provides the files you need, but the best way is to generate one yourself according to the commands provided by YudongGuo.

**Comment by muxiddin19** [comment]
Hi! Could you generate the file? In my case when I run the process data I faced the same issue. Is there some solution?
