### ISSUE TITLE
Driving the target person with an audio input 

### ISSUE THREAD

**Issue by hanweikung** [YudongGuo/AD-NeRF#53]
Hello,

Given an audio input, how do I render the full length of animation of the target person? I tried the command in the README, but it seemed only part of the animation was rendered.

`python NeRFs/TorsoNeRF/run_nerf.py --config dataset/$id/TorsoNeRFTest_config.txt --aud_file=${deepspeechfile.npy} --test_size=-1`

**Comment by YudongGuo** [comment]
Hi, please refer to #44

**Comment by hanweikung** [comment]
Thank you for your answer. It works now
