### ISSUE TITLE
What is ${deepspeechfile.npy}?

### ISSUE THREAD

**Issue by psuu0001** [YudongGuo/AD-NeRF#56]
I'm very appreciate for your excellent work! But when I tried to run the command below, the error came up , showing bad substitution error. That seems I lost the deepspeechfile.npy file. Can someone tells me where to get this file?

python NeRFs/TorsoNeRF/run_nerf.py --config dataset/$id/TorsoNeRFTest_config.txt --aud_file=${deepspeechfile.npy} --test_size=-1

bash: --aud_file=${deepspeechfile.npy}: bad substitution

**Comment by YudongGuo** [comment]
Hi, here $id means the filename of the target video, e.g. Obama. ${deepspeechfile.npy} means the deepspeech feature file extracted from audio (see [sample code](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/process_data.py#L66)).

**Comment by psuu0001** [comment]
Thanks so much for your reply! It really helps!
