### ISSUE TITLE
About the output

### ISSUE THREAD

**Issue by supy0001** [YudongGuo/AD-NeRF#57]
Dear author, I'm rookie in AI. When I run the last commad below, I only get the result in Obama/logs/Obama_com/test_aud_rst. The result is only a 30 seconds video with the outline of Obama. Is that right?

(LJ001-0001.npy is my customized audio input)
python NeRFs/TorsoNeRF/run_nerf.py --config dataset/vids/TorsoNeRFTest_config.txt --aud_file=LJ001-0001.npy--test_size=-1

![WechatIMG790](https://user-images.githubusercontent.com/94920559/143062205-ae754564-5a91-4955-a46b-be59bfb4ad7d.jpeg)

**Comment by YudongGuo** [comment]
I guess there were no pretrained models. You should put the pretrained models into folder dataset/Obama/logs/logs_torso/.
