### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by psuu0001** [YudongGuo/AD-NeRF#58]
'When I ran the “bash process_data.sh Obama” command, the error came up   Self.renderer should be a class so that it can accept the "mesh" and inference the image result. But self.renderer = self.get_render(batch_size) returns a "None" ,then whatever the mesh is, the result is None and error comes up. Did some one have the same problem like me？

Traceback (most recent call last):
  File "data_util/face_tracking/face_tracker.py", line 224, in <module>
    sel_light.to(device_render))  # （[50,27]）
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/supy/AD-NeRF-master/data_util/face_tracking/render_3dmm.py", line 216, in forward
    rendered_img=self.renderer(mesh)
TypeError: 'NoneType' object is not callable

**Comment by VishLivecoder** [comment]
Did u get a solution for this?

**Comment by psuu0001** [comment]
It's the problem of pytorch3d version

**Comment by shaoshengsong** [comment]
https://flyfish.blog.csdn.net/article/details/121979096
@psuu0001  I'm sure you're dealing with a match between cuda and cudnn,pytorch and pytorch3d.

**Comment by psuu0001** [comment]
> https://flyfish.blog.csdn.net/article/details/121979096 @psuu0001 I'm sure you're dealing with a match between cuda and cudnn,pytorch and pytorch3d.

Yes,it's the pytorch3d version problem.
