### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by islamikoo** [YudongGuo/AD-NeRF#59]
excuse me,
I ran the first command to preprocess the data but I don't want to retrain the whole model again
where should i put the pretrained models?

**Comment by YudongGuo** [comment]
Hi, you should put them to dataset/Obama/logs/logs_torso/ folder. Please refer to [data_util](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/process_data.py#L190), [NeRF_model](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/TorsoNeRF/run_nerf.py#L786).

**Comment by ZziTaiLeo** [comment]
> Hi, you should put them to dataset/Obama/logs/logs_torso/ folder. Please refer to [data_util](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/process_data.py#L190), [NeRF_model](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/TorsoNeRF/run_nerf.py#L786).

Excuse me ! I just use your pretrained model which is named 600000_body.tar to render, but it still mismatch, as your response on #60 , should I change the pts_linears size? Or I retrain two Nerfs with  Obama.mp4 ?

**Comment by ZziTaiLeo** [comment]
> > Hi, you should put them to dataset/Obama/logs/logs_torso/ folder. Please refer to [data_util](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/process_data.py#L190), [NeRF_model](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/TorsoNeRF/run_nerf.py#L786).
> 
> Excuse me ! I just use your pretrained model which is named 600000_body.tar to render, but it still mismatch, as your response on #60 , should I change the pts_linears size? Or I retrain two Nerfs with Obama.mp4 ?

#42  I got the solution.
