### ISSUE TITLE
cpu

### ISSUE THREAD

**Issue by xzkzdx** [YudongGuo/AD-NeRF#6]
GIVE CPU VIRSION

**Comment by RobinRenggli** [comment]
From my experience with NeRFs, I don't think they are suited for being trained with a CPU. It's highly parallel and the training already takes a while, unless you have multiple high end GPUs.

**Comment by xzkzdx** [comment]
I mean to run demo with CPU, not training

**Comment by RobinRenggli** [comment]
Wouldn't that still involve rendering the output? The rendering takes 20-30 seconds per frame on my GPU (GTX 1070). If you did this on a CPU, it would take forever.

**Comment by GzuPark** [comment]
Do respect to the researcher. Be proud of the researcher from your country.
Also, the code, which you can run easily, mostly does not allow to use commercially and share in this field.

**Comment by xzkzdx** [comment]
What size of GPU are you using

**Comment by YudongGuo** [comment]
> What size of GPU are you using

I'm using a single RTX 3090. For inference time with different devices please refer to #8.
