### ISSUE TITLE
Training Head cause Function PowBackward0 return nan value

### ISSUE THREAD

**Issue by GeogYu** [YudongGuo/AD-NeRF#62]
Hi, I've pre processed the data with my own video. After the video is pre processed, I tried to run the training head with provided code, it is giving a PowBackward0 error. I am running the code on Google Colab. 
![image](https://user-images.githubusercontent.com/41907837/143728677-a4f3cba2-080d-4283-9e2c-2b65d4b2ed20.png)
 
![image](https://user-images.githubusercontent.com/41907837/143728689-b4fef775-a682-40f3-acf2-a8e9d286a2c0.png)

**Comment by VishLivecoder** [comment]
Can you please tell me what you did for this

**Comment by GeogYu** [comment]
> Can you please tell me what you did for this

What I did is to modify the video encoding and fps of the video, and it fixed the problem. I need to check the details on it
