### ISSUE TITLE
No Faces were detected

### ISSUE THREAD

**Issue by islamikoo** [YudongGuo/AD-NeRF#65]
Hello,
I've tried a couple of videos which have been suggested in #33 
But I keep getting the same error at processing data 

--- Step 2: detect landmarks ---
/usr/local/envs/adnerf/lib/python3.7/site-packages/face_alignment/api.py:132: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
Traceback (most recent call last):
  File "data_util/process_data.py", line 100, in <module>
    if len(preds) > 0:
TypeError: object of type 'NoneType' has no len()

I don't think you got the same error unless you wouldn't have suggested them so any idea what's wrong?

**Comment by YudongGuo** [comment]
Hi, it's due to that there are no faces in the frame. You can avoid it by first checking if 'preds is None'.

**Comment by islamikoo** [comment]
thank you this solved it
