### ISSUE TITLE
Has anyone faced 'CUDA out of memory' problem due to the face_alignment.FaceAlignment function?

### ISSUE THREAD

**Issue by LeeChangki** [YudongGuo/AD-NeRF#66]
I would like to let you know a minor issue and how to fix it.

I am using two gtx 1080 ti(8GB), but the face_alignment package may not support using multi GPU.
And, I figure out that the obama example uses over 8GB memory of GPU to find landmarks that causes 'CUDA out of memory'.

So, I recommend to use 
`face_alignment.LandmarksType._2D,` flip_input=False, device='cpu')
instead of,
`face_alignment.LandmarksType._2D, flip_input=False)
in step 2: detect landmarks(process_data.py)
for someone using 8GB memory GPU.

This may slower than using GPU, but not that much and it works!

**Comment by shaoshengsong** [comment]
https://flyfish.blog.csdn.net/article/details/121979096   
He encountered the same problem as you. The individual orders in his cloud disk solved the problem.
