### ISSUE TITLE
Can't render length longer than training audio

### ISSUE THREAD

**Issue by FieldsYeh** [YudongGuo/AD-NeRF#68]
Hello,

From the source code [here](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/TorsoNeRF/run_nerf.py#L847) , seems the Render can't  render with a long audio input than the training source.  for exampe if the training source video only 10s, then input render audio time should not longer than 10s.

**Comment by islamikoo** [comment]
Same issue .. could you find a solution?

**Comment by FieldsYeh** [comment]
It's better to have a longer training video.
