### ISSUE TITLE
KeyError: "The name 'deepspeech/logits:0' refers to a Tensor which does not exist. 

### ISSUE THREAD

**Issue by FrancisChen888** [YudongGuo/AD-NeRF#69]
While excute --- Step1: extract images from vids ---

Traceback (most recent call last):
  File "data_util/deepspeech_features/extract_ds_features.py", line 128, in <module>
    main()
  File "data_util/deepspeech_features/extract_ds_features.py", line 120, in main
    extract_features(
  File "data_util/deepspeech_features/extract_ds_features.py", line 80, in extract_features
    conv_audios_to_deepspeech(
  File "/data/chenxianhao/AD-NeRF/data_util/deepspeech_features/deepspeech_features.py", line 41, in conv_audios_to_deepspeech
    graph, logits_ph, input_node_ph, input_lengths_ph = prepare_deepspeech_net(
  File "/data/chenxianhao/AD-NeRF/data_util/deepspeech_features/deepspeech_features.py", line 105, in prepare_deepspeech_net
    logits_ph = graph.get_tensor_by_name("deepspeech/logits:0")
  File "/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3931, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3755, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3795, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "

KeyError: "The name 'deepspeech/logits:0' refers to a Tensor which does not exist. The operation, 'deepspeech/logits', does not exist in the graph."

**Comment by 649459021** [comment]
Hey, What exactly did u do to resolve the issue?.

**Comment by sstzal** [comment]
Have you solved this problem?

**Comment by DuNGEOnmassster** [comment]
I wonder have you solved this problem too.

**Comment by flyingshan** [comment]
Downgrading tensorflow-gpu to 1.15.0 helped me solve this problem.

**Comment by Ela2Zofia** [comment]
Look for "logits:0" instead of "deepspeech/logits:0" will do the trick. This can be found after inspecting the name of all the nodes in the graph.

**Comment by rogerle** [comment]
tensorflow-gpu to 1.15.0 is right

**Comment by cucdengjunli** [comment]
mark

**Comment by aaaastark** [comment]
> While excute --- Step1: extract images from vids ---
> 
> Traceback (most recent call last): File "data_util/deepspeech_features/extract_ds_features.py", line 128, in main() File "data_util/deepspeech_features/extract_ds_features.py", line 120, in main extract_features( File "data_util/deepspeech_features/extract_ds_features.py", line 80, in extract_features conv_audios_to_deepspeech( File "/data/chenxianhao/AD-NeRF/data_util/deepspeech_features/deepspeech_features.py", line 41, in conv_audios_to_deepspeech graph, logits_ph, input_node_ph, input_lengths_ph = prepare_deepspeech_net( File "/data/chenxianhao/AD-NeRF/data_util/deepspeech_features/deepspeech_features.py", line 105, in prepare_deepspeech_net logits_ph = graph.get_tensor_by_name("deepspeech/logits:0") File "/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3931, in get_tensor_by_name return self.as_graph_element(name, allow_tensor=True, allow_operation=False) File "/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3755, in as_graph_element return self._as_graph_element_locked(obj, allow_tensor, allow_operation) File "/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3795, in _as_graph_element_locked raise KeyError("The name %s refers to a Tensor which does not "
> 
> KeyError: "The name 'deepspeech/logits:0' refers to a Tensor which does not exist. The operation, 'deepspeech/logits', does not exist in the graph."


The solution is here. Use the latest Tensorflow, etc packages (13-08-2025)
```python
tf.import_graph_def(graph_def, name="deepspeech")
logits_ph = graph.get_tensor_by_name("logits:0")
input_node_ph = graph.get_tensor_by_name("input_node:0")
input_lengths_ph = graph.get_tensor_by_name("input_lengths:0")
```
