### ISSUE TITLE
Effect of input video length on output quality

### ISSUE THREAD

**Issue by RobinRenggli** [YudongGuo/AD-NeRF#7]
I was wondering if you tested how the length of the input video affects the quality of the output. From my experience with similar models, lowering the number of training frames lowers the quality of the output (as would be expected).

Did you try training on a very long/short input video? I know the paper mentions most clips where of length 2-3 minutes, which is roughly 3000-5000 frames. Is this by choice, because it produces optimal results, or arbitrary? When I trained with a 1.5 minute long video, the results seemed not as good as in the Obama example.

If you did not test this, I'm happy to do it and report the results.

**Comment by YudongGuo** [comment]
Hi, I didn't do strict evaluations on the effect of video length. The longest video I trained was 9mins (about 11000 frames) and the shortest was 2mins (about 2500 frames). As expected, more video frames lead to better results. And for the result of 2 mins video, there were obvious artifacts (especially in the boundary between head and torso).

It's great that you are kind to do the evaluation and that will be very helpful. Thanks!
