### ISSUE TITLE
如何利用音频驱动

### ISSUE THREAD

**Issue by FrancisChen888** [YudongGuo/AD-NeRF#70]
在您的论文中有提到利用音频驱动视频中的任务，想问一下您发布的代码是没有包含这一部分吗？
如果包含的话如何进行相应的操作呢？

**Comment by YudongGuo** [comment]
Hi, please refer to ReadMe 'Drive the target person with another audio input' and you need to run [deepspeech](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/process_data.py#L69) for the speech feature.

**Comment by FrancisChen888** [comment]
Thanks for your guidance.It really helps a lot.
