### ISSUE TITLE
速度主要取决于显卡算力，在3090上跑数据处理大概要2个小时，如果用算力比较低的显卡的话这个时间也是正常的。

### ISSUE THREAD

**Issue by stabling** [YudongGuo/AD-NeRF#71]
速度主要取决于显卡算力，在3090上跑数据处理大概要2个小时，如果用算力比较低的显卡的话这个时间也是正常的。

_Originally posted by @YudongGuo in https://github.com/YudongGuo/AD-NeRF/issues/25#issuecomment-901607557_

**Comment by stabling** [comment]
你好，我想问下，这里的两个小时是指head和torso上面的总时间吗？这个时间对应的训练迭代次数这些参数是什么，可以发一下吗？

**Comment by YudongGuo** [comment]
你好，这个是数据预处理的时间，不是训练时间，训练一般要一到两天。
