### ISSUE TITLE
评价head和torso的训练指标

### ISSUE THREAD

**Issue by stabling** [YudongGuo/AD-NeRF#72]
你好，我想问一下有什么评价head和torso的训练指标吗？我注意到只有psnr和loss，而这两个指标反馈的结果和实际情况不同，请问有提供训练过程中保留结果图像的东西吗？或者一些其他的中间结果？谢谢

**Comment by stabling** [comment]
另外，我还有个问题。我用其他的人训练，最后得到的结果是整体都很模糊的。是训练的次数不够还是其他的原因？

**Comment by YudongGuo** [comment]
你好，在每经过i_testset迭代次数时，会保存在验证集上的渲染结果。[code](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/HeadNeRF/run_nerf.py#L945)

模糊问题可能是由于迭代次数不够，也可能是肩膀运动幅度较大等。

**Comment by stabling** [comment]
> 你好，在每经过i_testset迭代次数时，会保存在验证集上的渲染结果。[code](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/HeadNeRF/run_nerf.py#L945)
> 
> 模糊问题可能是由于迭代次数不够，也可能是肩膀运动幅度较大等。

好的，感谢解答！
