### ISSUE TITLE
How to change the view direction of the generated images?

### ISSUE THREAD

**Issue by KingSF5** [YudongGuo/AD-NeRF#76]
作者 您好 请问如何生成新视角呢

**Comment by YudongGuo** [comment]
hello，可以调整渲染时输入的pose来生成，具体可以调整[此处](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/TorsoNeRF/run_nerf.py#L836)的adjust_poses和adjust_poses_torso

**Comment by KingSF5** [comment]
> hello，可以调整渲染时输入的pose来生成，具体可以调整[此处](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/NeRFs/TorsoNeRF/run_nerf.py#L836)的adjust_poses和adjust_poses_torso

好的，我去试试，感谢您的解答！

**Comment by astroartisan** [comment]
Hello @KingSF5 @YudongGuo ,

How do I edit the view direction?
