### ISSUE TITLE
为什么渲染出的视频长度和输入的音频长度不一致？

### ISSUE THREAD

**Issue by CheaterScript** [YudongGuo/AD-NeRF#77]
你好，我想请教一下为什么我输入43秒的音频去渲染，结果只得到了27秒的视频呢？

**Comment by YudongGuo** [comment]
你好，渲染的长度跟两个参数有关，test_pose_file和test_size，请确保test_pose_file中姿态帧数对应时间大于43s且test_size设为-1。
