### ISSUE TITLE
Estimated iteration of model convergence

### ISSUE THREAD

**Issue by NIRVANALAN** [YudongGuo/AD-NeRF#78]
Hi, thanks for this good work.

I am training your model from scratch given the offical HeadNeRF.txt config, and may I know the estimated iteration of convergence? I trained for 1w iteration and it's still not converging yet. The PSNR is around 19.

Looking forward to your comments

**Comment by YudongGuo** [comment]
Hi, please refer to #3. It's recomended to use a pretrained model for initialization.
