### ISSUE TITLE
Torso training cannot start

### ISSUE THREAD

**Issue by tearscoco** [YudongGuo/AD-NeRF#79]
Congratulations on your great work!

I am trying to train your model from scratch with my own data to understand the whole pipepline. The preprocessing and head NeRF went well. However, when I try to train the torsor NeRF with pretrained head and torso ckpts, it cannot start at all. The following info appeared and then it stopped training.

$python NeRFs/TorsoNeRF/run_nerf.py --config dataset/cctv/TorsoNeRF_config.txt
Found ckpts ['/dump/2/zhule.zhl/gitWorks/AD-NeRF/dataset/cctv/logs/cctv_com/120000_head.tar']
Reloading from /dump/2/zhule.zhl/gitWorks/AD-NeRF/dataset/cctv/logs/cctv_com/120000_head.tar
Not ndc!
load audattnet
Found ckpts ['/dump/2/zhule.zhl/gitWorks/AD-NeRF/dataset/cctv/logs/cctv_com/600000_body.tar']
Reloading from /dump/2/zhule.zhl/gitWorks/AD-NeRF/dataset/cctv/logs/cctv_com/600000_body.tar
Not ndc!
Begin
TRAIN views are [   0    1    2 ... 5863 5864 5865]
VAL views are [5866 5867 5868 5869 5870 5871 5872 5873]
0it [00:00, ?it/s]

I appreciate it if you could help look into this issue.

Thanks!!

**Comment by tearscoco** [comment]
To make it clearer, I try to delete both pretrained ckpts or just left head ckpts, it worked fine.

As long as I put the pretrained torso ckpts from you in the dir, it stopped working : (

I don't know whether I did anything wrong with loading torso ckpt as I followed the instruction [here](https://github.com/YudongGuo/AD-NeRF/issues/30#issuecomment-910119026).

Please help!

**Comment by YudongGuo** [comment]
Hi, I have no idea how to solve this. Since it worked if you deleted the pretrained torso model, you can use the generated model trained in this way.

**Comment by mumukawayi** [comment]
Try to change the run_nerf.py in TorsoNerf file, variable "--N_iters" default value from 400000 to 1000000. 
I guess it is because the iteration time was set to 400000, while you have a 600000 checkpoint, change the iteration times may help.

**Comment by tearscoco** [comment]
> Try to change the run_nerf.py in TorsoNerf file, variable "--N_iters" default value from 400000 to 1000000. I guess it is because the iteration time was set to 400000, while you have a 600000 checkpoint, change the iteration times may help.

Thanks very much for your kind suggestion. However, it didn't seem to work in my case. But thank God when I trained torso from scratch with head ckpt, it actually worked in the end. And after training my own torso model, the ckpts could also be utilized for initialization.

**Comment by tearscoco** [comment]
> 

Thanks for your kind reply. I trained my own torso from scratch and it worked!

**Comment by l-mengwei** [comment]
> > 
> 
> Thanks for your kind reply. I trained my own torso from scratch and it worked!

Hello, I would like to ask you a question. My head nerf network trains fine, but when I train the torsonerf network, it still only has the head and no shoulder parts. Looking forward to your reply, thank you very much.

**Comment by PeterFanFan** [comment]
> > > 
> > 
> > 
> > Thanks for your kind reply. I trained my own torso from scratch and it worked!
> 
> Hello, I would like to ask you a question. My head nerf network trains fine, but when I train the torsonerf network, it still only has the head and no shoulder parts. Looking forward to your reply, thank you very much.

Hello, I aslo met this problem, do you have solved it?  Looking forward to your reply, thank you very much.
