### ISSUE TITLE
Expected Inference Time

### ISSUE THREAD

**Issue by saslamsameja** [YudongGuo/AD-NeRF#8]
Hi @YudongGuo, I wanted to know what is the expected inference time to generate output for let's say 300 frames or 12sec video. For me, it took around 5 hours to produce the output of duration 12sec [300 frames]. Is this the expected time or am I missing something? Thanks.

**Comment by YudongGuo** [comment]
Hi, it depends on the output resolution and the computation power of your GPU. For the Obama example (450x450), it takes about one hour to generate 300 frames with a single RTX 3090.

**Comment by RobinRenggli** [comment]
I can add the time it takes on a GeForce 1060. For the Obama example, it takes me a little under 30 seconds per frame, i.e. about 2.5 times longer than on the RTX 3090. 

I can offer more precise measures if it helps, these are just rough estimates.

**Comment by wode123** [comment]
> Hi, it depends on the output resolution and the computation power of your GPU. For the Obama example (450x450), it takes about one hour to generate 300 frames with a single RTX 3090.

  Does that mean that it also takes me an hour to generate a different voice-driven target?

**Comment by YudongGuo** [comment]
> > Hi, it depends on the output resolution and the computation power of your GPU. For the Obama example (450x450), it takes about one hour to generate 300 frames with a single RTX 3090.
> 
> Does that mean that it also takes me an hour to generate a different voice-driven target?

Yes, the time is almost the same.

**Comment by wode123** [comment]
> > > Hi, it depends on the output resolution and the computation power of your GPU. For the Obama example (450x450), it takes about one hour to generate 300 frames with a single RTX 3090.
> > 
> > 
> > Does that mean that it also takes me an hour to generate a different voice-driven target?
> 
> Yes, the time is almost the same.
I also have a small question, is the final input must be .npy format audio files why can not directly enter .wav files

**Comment by RobinRenggli** [comment]
I'll just add that this is normal for NeRFs and is not something unique to this model; it's the volumetric rendering that takes this long.

**Comment by YudongGuo** [comment]
> > > > Hi, it depends on the output resolution and the computation power of your GPU. For the Obama example (450x450), it takes about one hour to generate 300 frames with a single RTX 3090.
> > > 
> > > 
> > > Does that mean that it also takes me an hour to generate a different voice-driven target?
> > 
> > 
> > Yes, the time is almost the same.
> > I also have a small question, is the final input must be .npy format audio files why can not directly enter .wav files

It could be wav input just by adding the step 0 of process data.
