### ISSUE TITLE
Bin size issue in step 6

### ISSUE THREAD

**Issue by mumukawayi** [YudongGuo/AD-NeRF#81]
When I was trying to generate my own dataset with an one-minute video, during step 6, after find best focal 1200, it raised lots of same error messages:
`Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to -1 to use the naïve rasterization.`
But I didn't find where I could set the bin_size. Since the track_params.pt in step was not generated due to the error, I couldn't move forward. Could anybody help?

**Comment by mumukawayi** [comment]
https://user-images.githubusercontent.com/62782802/155937120-af8bc1ce-6b6f-4e4c-8d6c-7e4338f6011b.mp4

Here is the original mp4 file I used to generate dataset.

**Comment by YudongGuo** [comment]
Hi, you can add the suggested options [here](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/face_tracking/render_3dmm.py#L123). Also note that the code only supports the video with squared resolution.

**Comment by mumukawayi** [comment]
Solved it by change the video to squared resolution, thanks a lot for this great work!

**Comment by mumukawayi** [comment]
> Hi, you can add the suggested options [here](https://github.com/YudongGuo/AD-NeRF/blob/9fdcd7e1352aa74e26baa8e60c862f9fbd7933bf/data_util/face_tracking/render_3dmm.py#L123). Also note that the code only supports the video with squared resolution.

Sorry for bother again, could you please explain it for me that why the video only support squared resolution?

**Comment by YudongGuo** [comment]
The face tracking step only supports squared resolution (more specifically, the rendering code) and I have no time to fix it recently.

**Comment by yaoyuan13** [comment]
> 

I modified the video to be squared resolution, but still meet the same error, any revisions to do?

**Comment by alchemician** [comment]
@YudongGuo same here, I modified to sqaure resolution, but no luck. any code suggestions on how to do square resolution exactly or any ideas to fix the issue once and for all?
