### ISSUE TITLE
你好我在执行第一条命令时报如下错是怎么回事？

### ISSUE THREAD

**Issue by TANGLONG2** [YudongGuo/AD-NeRF#83]
ResolvePackageNotFound: 
  - pytorch 1.8.1 py3.7_cuda11.1_cudnn8.0.5_0
  - cudatoolkit >=11.1,<11.2
  - __glibc >=2.17,<3.0.a0
  - libstdcxx-ng 9.3.0 hd4cf53a_17
  - __glibc >=2.17
  - libgcc-ng 9.3.0 h5101ec6_17
  - __glibc >=2.17
  - libgfortran-ng 7.5.0 ha8ba4b0_17
  - __glibc >=2.17
  - cudatoolkit 11.1.1 h6406543_8
  - __glibc >=2.17,<3.0.a0

为什么会连pytorch都无法安装

**Comment by YudongGuo** [comment]
应该是版本与环境不兼容，可以把版本号去掉。
