### ISSUE TITLE
why is there no HeadNeRFTest_config_file in process_data.py ?

### ISSUE THREAD

**Issue by l-mengwei** [YudongGuo/AD-NeRF#88]
Hello, I have a question to ask you, why is there only ComNeRFTest_config_file in the process_data.py file but no HeadNeRFTest_config_file ?

**Comment by l-mengwei** [comment]
> Hello, I have a question to ask you, why is there only ComNeRFTest_config_file in the process_data.py file but no HeadNeRFTest_config_file ?

**Comment by rlgnswk** [comment]
Hi, Did you find the reason why it works like that?
